console.log({a:1,b:2})
console.table({a:1,b:2})
console.log("hello world")
console.warn("this is warning")
console.error("this is error")
console.clear()
console.time("aayush")
    console.log("hello world")
    console.log("hello world")
    console.log("hello world")
console.timeEnd("aayush")